# After creating this file if you run  
# "mlflow run ." then it will create a conda env with the below name and dependencies

name: mlflow_env
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow==1.26